name: Android Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Give gradlew permission
        run: chmod +x android/gradlew

      - name: Build release APK
        run: cd android && ./gradlew assembleRelease --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SocialFundApp-release-apk
          path: android/app/build/outputs/apk/release/*.apk